- src/core/Hypridle.cpp
- src/core/Hypridle.hpp
I'm not sure if this was intentional or not, but when going over the code of hypridle, I noticed that the inhibit cookies that are created and sending back to dbus aren't actually getting registered, so uninhibit never detects a valid cookie.
Unless this was done intentionally, because the support isn't yet ready or whatever, these cookies should really be getting registered once created.
> Actually register inhibit cookies

- src/core/Hypridle.cpp
On non-systemd distros elogind may not be installed.
```c++
$ hypridle
[...]
[LOG] wayland done, registering dbus
Abort
(lldb) bt
* thread #1, name = 'hypridle', stop reason = signal SIGABRT
* frame #0: 0x00000008259546aa libc.so.7`__sys_thr_kill at thr_kill.S:4
frame #1: 0x00000008258c21a4 libc.so.7`__raise(s=6) at raise.c:48:10
frame #2: 0x00000008259834f9 libc.so.7`abort at abort.c:61:8
frame #3: 0x0000000823f66fe9 libcxxrt.so.1`report_failure(err=<unavailable>, thrown_exception=0x00002abde72930c0) at exception.cc:734:5
frame #4: 0x00000008234c7560 libsdbus-c++.so.1`sdbus::internal::Proxy::SyncCallReplyData::waitForMethodReply(this=0x00000008203c3a58) at Proxy.cpp:194:9
frame #5: 0x00000008234c68b2 libsdbus-c++.so.1`sdbus::internal::Proxy::sendMethodCallMessageAndWaitForReply(this=0x000 …
```
> Gracefully exit without (e)logind

- src/core/Hypridle.cpp
Some simple fixes to `spawn` to check the correct PID before displaying error message.
> Fix typo and check correct grandchild PID in spawn()

- CMakeLists.txt
- README.md
- systemd/hypridle.service.in
Hypridle can now be started and managed using systemd with
```sh
systemctl --user enable --now hypridle.service
```
This is useful as it allows an easier way to manage services that, like this, always run in the background. This way `systemctl start/stop/restart` commands can be used instead of `killall hypridle / nohup hypridle` or similar. I slightly updated the README to mention this different usage possibility.
Before this is ready to be merged, though, I'd need some feedback on the way I am currently configuring and installing the service file (see `CMakeLists.txt` and `systemd/hypridle.service.in`). The configuration part is not currently working though, I'm not really sure what I should be using to point at the directory the hypridle executable can be found in (usually …
> Added systemd service

- CMakeLists.txt
This partially reverts https://github.com/hyprwm/hypridle/commit/dad6ac14df38bd8d449677e8f998970af211b8b0
What @fufexan  suggested with `${CMAKE_INSTALL_LIBDIR}/systemd/user` doesn't seem to work consistently, reverting to `"lib/systemd/user"` for now is 100% a better idea. It's also what https://github.com/hyprwm/xdg-desktop-portal-hyprland/blob/master/CMakeLists.txt uses, which is why I was initially also doing that instead of LIBDIR
> fix systemd service install path

- systemd/hypridle.service.in
Yeah, here I am again, sorry for the inconvenience. I hate cmake. Why do those variables only work sometimes? Nobody knows.
Anyway, BINDIR appears to be just as unreliable as LIBDIR. Great.
As usual @fufexan lmk if you know of anything better (or yk, at least something that works).
> fix systemd service exec path

- src/core/Hypridle.cpp
This PR implements listening for systemd-inhibit idle block inhibits.
For simplicity I've decided that there's no need to retrieve details about inhibitors using `ListInhibitors` method in `org.freedesktop.login1.Manager` interface and it's enough to get list of block inhibit types using `BlockInhibited` property. This property is monitored using `PropertyChanged` signal. Also the property is read on hypridle start, so if there is already an inhibitor active, then idle is going to be inhibited right away.
This simplification causes that even if there are multiple idle inhibitors active, they're going to be only counted as one in hypridle (it inhibits on first active inhibitor and releases inhibit on deactivation of the last one). To check the list of active inhibitors one can use …
> Add support for systemd-inhibit idle block inhibits

- README.md
- src/config/ConfigManager.cpp
- src/core/Hypridle.cpp
- src/core/Hypridle.hpp
This MR introduces separate `ignore_systemd_inhibit` configuration parameter, which controls whether hypridle respects systemd inhibits or not.
Second change is that both `ignore_dbus_inhibit` and `ignore_systemd_inhibit` parameters are processed early in `CHypridle::setupDBUS()`. This means that if `ignore_dbus_inhibit` is set, then no attempt to register `org.freedesktop.ScreenSaver` object is made, but hypridle will still respect the systemd.
This gives the ability to use a different daemon which registers this object in parallel to hypridle. One example of such daemon would be https://github.com/bdwalton/inhibit-bridge, which registers its own `ScreenSaver` object and forwards ScreenSaver inhibits as systemd inhibits. Systemd inhibits are more flexible, as there can be multiple …
> Use separate `ignore_systemd_inhibit` config param for systemd. Register ScreenSaver object under multiple paths.

- src/core/Hypridle.cpp
This addresses #26.
Got annoyed with monitor staying on after video is over. It would be better to use [idle-inhibit-unstable-v1](https://wayland.app/protocols/idle-inhibit-unstable-v1) with a fake surface and let Hyprland just reset and halt timers, but I'm not writing that. The conditions shouldn't trigger too often anyways, so with <10 hooks on average it should be harmless.
Tested for about 2 days, but I don't do c++ and wayland-proto, so check for sanity please. If you don't like that copy-paste and want me to create clean methods for clearing notifications and re-registering them separately, do tell.
(and if someone manages to hot-reload config in an idle state, that's on them)
> Reset timers after inhibitor has been taken off if idled

- src/core/Hypridle.cpp
Hypridle currently exits on systems without logind, but its functionality doesn't appear to depend on it.
This PR is marked as a draft because I haven't tested it on a system with logind yet, and I'm not sure if where the matches are moved is the best place.
> Fix running without logind

- CMakeLists.txt
I'm guessing this was a copy-paste typo.  I just tried to install the AUR packages for hypridle-git and hyprlock-git and they are colliding in /usr/share/hypr/hyprlock.conf - this should fix it!
> typo fix hyprlock->hypridle

- src/main.cpp
This doesn't fix a compile error; it is already included because of `ConfigManager.hpp` including it. However, that should not be relied on as logging is also directly used in the main function.
> Include Log.hpp in main

- src/helpers/Log.hpp
Currently cout is never flushed. This is a problem because the actual flush timing is implementation defined and also changes whether it's piped or not. If you try to run `hypridle | tee idle.log` (simple example of trying to persist the log during development), then there is no log output.
This also means if hypridle were to crash, you don't lose all the messages that had the misfortune of not being already flushed.
Also looks like this same issue is present in Hyprland? Although over there it's less of an issue because of rollinglog and the file writer.
> Flush cout buffer automatically

- nix/default.nix
Needed for https://github.com/NixOS/nixpkgs/pull/214906. I confirmed this builds on current nixos-unstable-small and nixos-unstable (i.e. with and without the wayland-scanner split).
> nix: add wayland-scanner native build input

- src/main.cpp
Maybe also add some warnings if more than one config file is provided ?
> Do not crash if the last CLI parameter was -c

- CMakeLists.txt
- nix/overlays.nix
- src/core/Hypridle.cpp
> core: move to sdbus-cpp2

- src/core/Hypridle.cpp
> core: handleDbusScreensaver must return uint32

- .gitignore
- CMakeLists.txt
- README.md
- flake.lock
- flake.nix
- nix/default.nix
- nix/overlays.nix
- src/config/ConfigManager.cpp
- src/config/ConfigManager.hpp
- src/core/Hypridle.cpp
- src/core/Hypridle.hpp
- src/defines.hpp
Requires the protocol and https://github.com/hyprwm/Hyprland/pull/9092
TODO: 
If users use hypridle and hyprlock, this PR will fix https://github.com/hyprwm/hyprlock/issues/547 and https://github.com/hyprwm/hyprlock/issues/633 (dupe).
`general:inhibit_sleep` is 2 (auto) per default.
Hypridle will check if either `before_sleep_cmd` contains "hyprlock" or if `before_sleep_cmd` contains "lock-session" and `lock_cmd` contains "hyprlock".
In those cases, hypridle will inhibit sleep until we receive the locked event from hyprland-lock-notify-v1. This behavior can be manually selected with `general:inhibit_sleep=3` and should work for all session-lock apps. 
`general:inhibit_sleep=0` is the current behaviour.
``general:inhibit_sleep=1` will lock sleep until we launched the `before_sleep_cmd`.
> core: implement hyprlock-lock-notify-v1 functionality

- src/core/Hypridle.cpp
- src/core/Hypridle.hpp
So releasing the sleep inhibitor did not work properly so far, cause of forked fds.
That lead to suspend taking max delay seconds, which defaults to 5. (I used a `sleep 4 && hyprlock` to test that the system does not go sleep, so I did not notice.)
~~As can be seen in my comments, for some reason we still need to explicitly close the fd in the child process despite setting O_CLOEXEC, which is weird.~~
I removed the second fork cause we don't need it in hypridle, which also allowed to set SA_NOCLDWAIT and stuff which is nice to have for a daemon process.
> core: fix sleep delay and simplify process spawning

- src/core/Hypridle.cpp
and hint that hyprilde may already be running.
> core: log when ScreenSaver interface is already registered

- src/config/ConfigManager.cpp
- src/config/ConfigManager.hpp
- src/helpers/MiscFunctions.cpp
- src/helpers/MiscFunctions.hpp
Hey :wave: 
This PR implements #33.
a896871df5b31de8e4e83140ccb82feba5bdbc86: the code comes from hyprlock
8d4c6ead8fd9f6b51867df91e6a7837a3ab0bb41: implement a circular dependency protection. hyprlock (and hypridle without that commit) don't start and show no errors if there's a circular dependency.
> feat: support `source` option for additional config files

- src/core/Hypridle.cpp
> core: guard against dbus logind interface not existing and check if on_(un)lock_cmd is empty

- flake.lock
- src/config/ConfigManager.cpp
- src/core/Hypridle.cpp
config: general:ignore_wayland_inhibit (bool)
If the config value general:ignore_wayland_inhibit is true, the CCExtIdleNotifierV1 function used will be: sendGetInputIdleNotification. This instructs the compositor (hyprland) to return all idle/resume events, ignoring any Wayland inhibitors.
If the config value general:ignore_wayland_inhibit is false/unset, it will use the default function sendGetIdleNotification, which obeys Wayland inhibitors.
> Add ability to ignore Wayland idle inhibitors
